export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE"

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE"

export const EDIT_PRODUCT_REQUEST="EDIT_PRODUCT_REQUEST"
export const EDIT_PRODUCT_SUCCESS="EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAILURE="EDIT_PRODUCT_FAILURE"

export const SEARCH_PRODUCT_REQUEST="SEARCH_PRODUCT_REQUEST"
export const SEARCH_PRODUCT_SUCCESS="SEARCH_PRODUCT_SUCCESS"
export const SEARCH_PRODUCT_FAILURE="SEARCH_PRODUCT_FAILURE"


